
package jadsongonzaga.organize.view;

import jadsongonzaga.organize.controller.BuscaPacienteController;
import jadsongonzaga.organize.controller.ClienteViaCepWS;
import jadsongonzaga.organize.controller.EstadoController;
import jadsongonzaga.organize.controller.MunicipioController;
import jadsongonzaga.organize.controller.PacienteController;
import jadsongonzaga.organize.controller.Utils;
import jadsongonzaga.organize.exception.CepNaoEncontradoException;
import jadsongonzaga.organize.model.Acompanhante;
import jadsongonzaga.organize.model.Endereco;
import jadsongonzaga.organize.model.Estado;
import jadsongonzaga.organize.model.Municipio;
import jadsongonzaga.organize.model.Paciente;
import jadsongonzaga.organize.model.Pessoa;
import jadsongonzaga.organize.model.Tratamento;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author jadson
 */
public class PacienteView extends javax.swing.JDialog {

    /**
     * Creates new form AcompanhanteView
     * @param parent
     * @param modal
     */
    public PacienteView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        acao();
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraTarefa = new jadsongonzaga.organize.view.PanelBarraTarefa(eventos);
        panelAcompanhante = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcEscolaridade = new javax.swing.JComboBox<>();
        jdDataNascimento = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jcEstadoCivil = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jtQuantidadeFilhos = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jtConjuge = new javax.swing.JTextField();
        jcTipoMoradia = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jchRecebeRenda = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jtObservacao = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jtAcompanhante = new javax.swing.JTextField();
        jtTratamento = new javax.swing.JTextField();
        panelPessoa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jtTelefone = new javax.swing.JFormattedTextField();
        jtCelular = new javax.swing.JFormattedTextField();
        jtRg = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtRg1 = new javax.swing.JTextField();
        panelEndereco = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jtCep = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jtLogradouro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcEstado = new javax.swing.JComboBox();
        jcMunicipio = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paciente");
        setResizable(false);

        panelAcompanhante.setBorder(javax.swing.BorderFactory.createTitledBorder("Paciente"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Data de nascimento");

        jcEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Escolaridade");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Estado civil");

        jcEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Quandidade de filhos");

        jtQuantidadeFilhos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Cônjuge");

        jtConjuge.setText("jTextField1");

        jcTipoMoradia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Tipo de moradia");

        jchRecebeRenda.setText("Recebe renda");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Observação");

        jtObservacao.setText("jTextField2");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Acompante");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jadsongonzaga/organize/view/icones/ic_search_black_18dp_1x.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Tratamento");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jadsongonzaga/organize/view/icones/ic_add_black_18dp_1x.png"))); // NOI18N
        jButton2.setToolTipText("Adicionar informações do tratamento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtAcompanhante.setEditable(false);
        jtAcompanhante.setText("jTextField1");

        jtTratamento.setEditable(false);
        jtTratamento.setText("jTextField1");

        javax.swing.GroupLayout panelAcompanhanteLayout = new javax.swing.GroupLayout(panelAcompanhante);
        panelAcompanhante.setLayout(panelAcompanhanteLayout);
        panelAcompanhanteLayout.setHorizontalGroup(
            panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAcompanhanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addGap(4, 4, 4)
                .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAcompanhanteLayout.createSequentialGroup()
                        .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAcompanhanteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtQuantidadeFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAcompanhanteLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelAcompanhanteLayout.createSequentialGroup()
                                    .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcTipoMoradia, 0, 249, Short.MAX_VALUE)
                                        .addComponent(jtAcompanhante))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(jLabel22)
                                    .addGap(3, 3, 3)
                                    .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jchRecebeRenda)
                                        .addGroup(panelAcompanhanteLayout.createSequentialGroup()
                                            .addComponent(jtTratamento)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jtConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelAcompanhanteLayout.setVerticalGroup(
            panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcompanhanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jdDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtQuantidadeFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtConjuge)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcTipoMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jchRecebeRenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAcompanhanteLayout.createSequentialGroup()
                        .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(jtTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtAcompanhante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jtObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        panelPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa"));
        panelPessoa.setPreferredSize(new java.awt.Dimension(706, 226));

        jLabel2.setText("Identificador");

        jLabel3.setText("Nome");

        jLabel4.setText("Telefone");

        jLabel5.setText("Celular");

        jLabel6.setText("R.G.");

        jLabel7.setText("Email");

        jtId.setEditable(false);
        jtId.setText("jTextField1");

        jtNome.setText("jTextField2");

        try {
            jtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jtEmail.setText("jTextField4");

        jLabel8.setText("Profissão");

        javax.swing.GroupLayout panelPessoaLayout = new javax.swing.GroupLayout(panelPessoa);
        panelPessoa.setLayout(panelPessoaLayout);
        panelPessoaLayout.setHorizontalGroup(
            panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPessoaLayout.createSequentialGroup()
                        .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtRg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(2, 2, 2)
                        .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(jtRg1)))
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEmail)
                    .addComponent(jtNome))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelPessoaLayout.setVerticalGroup(
            panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoaLayout.createSequentialGroup()
                .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jtRg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelPessoaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtCelular, jtEmail, jtId, jtNome, jtRg, jtRg1, jtTelefone});

        panelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        panelEndereco.setPreferredSize(new java.awt.Dimension(709, 128));

        jLabel9.setText("CEP");

        try {
            jtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCepFocusLost(evt);
            }
        });

        jLabel10.setText("Logradouro");

        jLabel11.setText("Número");

        jLabel12.setText("Bairro");

        jLabel13.setText("Estado");

        jLabel14.setText("Município");

        jcEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEstadoActionPerformed(evt);
            }
        });

        jcMunicipio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelEnderecoLayout = new javax.swing.GroupLayout(panelEndereco);
        panelEndereco.setLayout(panelEnderecoLayout);
        panelEnderecoLayout.setHorizontalGroup(
            panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcEstado, 0, 195, Short.MAX_VALUE)
                    .addComponent(jtNumero)
                    .addComponent(jtCep))
                .addGap(18, 18, 18)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtBairro)
                    .addComponent(jtLogradouro)
                    .addComponent(jcMunicipio, 0, 432, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEnderecoLayout.setVerticalGroup(
            panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnderecoLayout.createSequentialGroup()
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEnderecoLayout.createSequentialGroup()
                        .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtCep, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtLogradouro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtBairro, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcEstado)
                            .addComponent(jcMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBarraTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAcompanhante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBarraTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAcompanhante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCepFocusLost

        //pesquisa o endereço apenas se não foi informado, validação para edição
        if (jtLogradouro.getText().isEmpty()) {
            evtBuscaCep();
        }
    }//GEN-LAST:event_jtCepFocusLost

    private void jcEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEstadoActionPerformed

        carregarMunicipios();
    }//GEN-LAST:event_jcEstadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        acompanhante();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        tratamento();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PacienteView dialog = new PacienteView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcEscolaridade;
    private javax.swing.JComboBox jcEstado;
    private javax.swing.JComboBox<String> jcEstadoCivil;
    private javax.swing.JComboBox jcMunicipio;
    private javax.swing.JComboBox<String> jcTipoMoradia;
    private javax.swing.JCheckBox jchRecebeRenda;
    private com.toedter.calendar.JDateChooser jdDataNascimento;
    private javax.swing.JTextField jtAcompanhante;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JFormattedTextField jtCelular;
    private javax.swing.JFormattedTextField jtCep;
    private javax.swing.JTextField jtConjuge;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtLogradouro;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextField jtObservacao;
    private javax.swing.JFormattedTextField jtQuantidadeFilhos;
    private javax.swing.JTextField jtRg;
    private javax.swing.JTextField jtRg1;
    private javax.swing.JFormattedTextField jtTelefone;
    private javax.swing.JTextField jtTratamento;
    private javax.swing.JPanel panelAcompanhante;
    private jadsongonzaga.organize.view.PanelBarraTarefa panelBarraTarefa;
    private javax.swing.JPanel panelEndereco;
    private javax.swing.JPanel panelPessoa;
    // End of variables declaration//GEN-END:variables

    EstadoController controllerEstado = new EstadoController();
    PacienteController controller = new PacienteController();
    Paciente paciente;
    private boolean novo = true;
    Acompanhante acompanhante;
    Tratamento tratamento;

    private void iniciar() {

        jcEstado.setModel(controllerEstado.obterModelCombo());
        carregarMunicipios();
        carregarCombos();
        modoInicial();

    }

    private void carregarMunicipios() {
        Estado obj = (Estado) jcEstado.getSelectedItem();
        jcMunicipio.setModel(new MunicipioController().obterModelCombo(obj));
    }

    private void carregarCombos() {
        jcEscolaridade.setModel(controller.obterModelComboEscolaridade());
        jcEstadoCivil.setModel(controller.obterModelComboEstadoCivil());
        jcTipoMoradia.setModel(controller.obterModelComboTipoMoradia());
    }

    private void evtBuscaCep() {
        ClienteViaCepWS clienteCep;
        try {
            clienteCep = new ClienteViaCepWS(jtCep.getText());
            jtBairro.setText(clienteCep.getBairro());
            jtLogradouro.setText(clienteCep.getLogradouro());
            Estado e = new EstadoController().obter(clienteCep.getUf());
            jcEstado.setSelectedItem(e);
            jcMunicipio.setSelectedItem(new MunicipioController().obter(clienteCep.getIbge()));
        } catch (CepNaoEncontradoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    public void setEndereco(Endereco endereco) {
        jtBairro.setText(endereco.getBairro());
        jtCep.setText(endereco.getCep());
        jtLogradouro.setText(endereco.getLogradouro());
        jtNumero.setText(endereco.getNumero());
        jcEstado.setSelectedItem(endereco.getMunicipio().getEstado());
        jcMunicipio.setSelectedItem(endereco.getMunicipio());
    }

    public Endereco getEndereco() {
        Endereco endereco = new Endereco();
        endereco.setBairro(jtBairro.getText());
        endereco.setCep(Utils.removeFormatacao(jtCep.getText()));
        endereco.setLogradouro(jtLogradouro.getText());
        endereco.setNumero(jtNumero.getText());
        endereco.setMunicipio((Municipio) jcMunicipio.getSelectedItem());

        return endereco;
    }

    public void setPessoa(Pessoa pessoa) {
        jtCelular.setText(pessoa.getCelular());
        jtRg.setText(pessoa.getRg());
        jtId.setText(String.valueOf(pessoa.getId()));
        jtNome.setText(pessoa.getNome());
        jtEmail.setText(pessoa.getEmail());
        jtTelefone.setText(pessoa.getTelefone());
    }

    public Pessoa getPessoa() {
        Pessoa pessoa = new Pessoa();
        pessoa.setCelular(Utils.removeFormatacao(jtCelular.getText()));
        pessoa.setRg(jtRg.getText());
        if (!jtId.getText().equals("")) {
            pessoa.setId(Integer.parseInt(jtId.getText()));
        }
        pessoa.setNome(jtNome.getText());
        pessoa.setEmail(jtEmail.getText());
        pessoa.setTelefone(Utils.removeFormatacao(jtTelefone.getText()));
        pessoa.setEndereco(getEndereco());

        return pessoa;
    }

    private Paciente getPaciente() {
        Paciente paci = new Paciente();
        paci.setAcompanhante(acompanhante);
        paci.setConjuge(jtConjuge.getText());
        paci.setDataNacimento(Utils.paraLocalDate(jdDataNascimento.getDate()));
        paci.setEscolaridade((Paciente.Escolaridade) jcEscolaridade.getSelectedItem());
        paci.setEstadoCivil((Paciente.EstadoCivil) jcEstadoCivil.getSelectedItem());
        paci.setTipoMoradia((Paciente.TipoMoradia) jcTipoMoradia.getSelectedItem());
        paci.setObservacao(jtObservacao.getText());
        
        paci.setQuatidadeFilho(Integer.parseInt(jtQuantidadeFilhos.getText()));
        paci.setRecebeRenda(jchRecebeRenda.isSelected());
        paci.setTratamento(tratamento);
        return paci;
    }
    
    private void setPaciente(Paciente paciente) {
  
        jtId.setText(String.valueOf(paciente.getPessoa().getId()));
        if(paciente.getAcompanhante() != null){
            acompanhante = paciente.getAcompanhante();
            jtAcompanhante.setText(acompanhante.toString());
        }
        jtConjuge.setText(paciente.getConjuge());
        jdDataNascimento.setDate(java.sql.Date.valueOf(paciente.getDataNacimento()));
        jcEscolaridade.setSelectedItem(paciente.getEscolaridade());
        jcEstadoCivil.setSelectedItem(paciente.getEstadoCivil());
        jcTipoMoradia.setSelectedItem(paciente.getTipoMoradia());
        jtObservacao.setText(paciente.getObservacao());
        
        setPessoa(paciente.getPessoa());
        jtQuantidadeFilhos.setText(String.valueOf(paciente.getQuatidadeFilho()));
        
        jchRecebeRenda.setSelected(paciente.isRecebeRenda());
        
        setPessoa(paciente.getPessoa());
        setEndereco(paciente.getPessoa().getEndereco());
        
        if(paciente.getTratamento() != null){
            tratamento = paciente.getTratamento();
            jtTratamento.setText(tratamento.toString());
        }

        
        
        
        
    }
    
    private void carregarDados(int id){
        paciente = controller.obter(id);
        setPaciente(paciente);
        
    }

    private void evtNovo() {
        UtilsView.limpaComponentes(panelPessoa);
        UtilsView.limpaComponentes(panelEndereco);
        UtilsView.limpaComponentes(panelAcompanhante);
        UtilsView.habilitaComponentes(panelPessoa, true);
        UtilsView.habilitaComponentes(panelEndereco, true);
        UtilsView.habilitaComponentes(panelAcompanhante, true);
        acompanhante = null;
        tratamento = null;
        paciente = null;
        jtNome.grabFocus();
        jtQuantidadeFilhos.setText("0");
    }
    
    private void modoInicial() {
        UtilsView.limpaComponentes(panelPessoa);
        UtilsView.limpaComponentes(panelEndereco);
        UtilsView.limpaComponentes(panelAcompanhante);
        jtNome.grabFocus();
        UtilsView.habilitaComponentes(panelPessoa, false);
        UtilsView.habilitaComponentes(panelEndereco, false);
        UtilsView.habilitaComponentes(panelAcompanhante, false);
        novo = true;
    }
    
    private void modoEditar() {
        
        UtilsView.habilitaComponentes(panelPessoa, true);
        UtilsView.habilitaComponentes(panelEndereco, true);
        UtilsView.habilitaComponentes(panelAcompanhante, true);
        jtNome.grabFocus();
    }

    EventosBarraTarefas eventos;

    private void acao() {
        eventos = new EventosBarraTarefas() {
            @Override
            public boolean salvar() {

                List<ComponenteInfo> componentes = new LinkedList<>();

                componentes.add(new ComponenteInfo(jtNome, "Nome"));
                componentes.add(new ComponenteInfo(jdDataNascimento, "Data de nascimento"));
                componentes.add(new ComponenteInfo(jtCep, "CEP"));
                componentes.add(new ComponenteInfo(jtLogradouro, "Logradouro"));
                componentes.add(new ComponenteInfo(jcMunicipio, "Cidade"));
                if (UtilsView.validaCamposObrigatorios(componentes)) {
                    Paciente pacie = getPaciente();
                    Pessoa pessoa = getPessoa();

                    pessoa.setEndereco(getEndereco());
                    pacie.setPessoa(pessoa);
                    if (!novo) {
                        pacie.getPessoa().getEndereco().setId(paciente.getPessoa().getEndereco().getId());
                    }
                    controller.salvar(pacie, novo);
                    modoInicial();
                    return true;
                }
                return false;

            }

            @Override
            public void novo() {
                evtNovo();
            }

            @Override
            public void cancelar() {
                modoInicial();
            }

            @Override
            public void editar() {
                modoEditar();
                novo = false;
            }

            @Override
            public boolean excluir() {
                int op = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o registro de: "+ paciente.getPessoa());
                if(op == 0){
                    controller.excluir(paciente);
                    modoInicial();
                }
                return op == 0;
            }

            @Override
            public void pesquisar() {
                evtPesquisar();
            }

            @Override
            public void confirmar() {
                
            }
        };
    }
    
    private void evtPesquisar(){
        BuscaPacienteController busca = new BuscaPacienteController();
        
        Buscar buscar = new Buscar(null, true, busca.getBuscaController());
        buscar.setVisible(true);
        int id = buscar.getId();
        if(id > 0){
            modoInicial();
            carregarDados(id);
        }
    }
    
    private void acompanhante() {
        AcompanhanteView acompanteView = new AcompanhanteView(null, true, true);
        if (paciente != null) {
            acompanhante = acompanteView.getAcompanhanteSelecionando(paciente.getAcompanhante());
        } else {
            acompanhante = acompanteView.getAcompanhanteSelecionando(null);
        }
        if (acompanhante != null) {
            jtAcompanhante.setText(acompanhante.toString());

        }
    }
    
    private void tratamento() {
        TratamentoView tratamentoView = new TratamentoView(null, true, paciente);
        
        tratamento = tratamentoView.getTratamentoSelecionado();
        if (tratamento != null) {
            jtTratamento.setText(tratamento.toString());

        }
    }
    
}
