/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jadsongonzaga.organize.view;

import jadsongonzaga.organize.controller.ServicoItemController;
import jadsongonzaga.organize.controller.TipoServicoController;
import jadsongonzaga.organize.controller.Utils;
import jadsongonzaga.organize.exception.DuplicidadeRegistroException;
import jadsongonzaga.organize.model.Servico;
import jadsongonzaga.organize.model.ServicoItem;
import jadsongonzaga.organize.model.TipoServico;
import java.time.format.DateTimeFormatter;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jadson
 */
public class ServicoItemView extends javax.swing.JDialog {

    /**
     * Creates new form ServicoItemView
     * @param parent
     * @param modal
     * @param servico
     */
    public ServicoItemView(java.awt.Frame parent, boolean modal, Servico servico) {
        super(parent, modal);
        initComponents();
        this.servico = servico;
        iniciar();
    }
    
    public ServicoItemView(java.awt.Frame parent, boolean modal, Servico servico, ServicoItem servicoItem) {
        super(parent, modal);
        initComponents();
        this.servico = servico;
        iniciar();
        setServicoItem(servicoItem);
        modoEditar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelServico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtIdServico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtDatahora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtPaciente = new javax.swing.JTextField();
        panelItem = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcTipoServico = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtQuantidade = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Serviço - Itens");
        setResizable(false);

        panelServico.setBorder(javax.swing.BorderFactory.createTitledBorder("Serviço"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Serviço");

        jtIdServico.setEditable(false);
        jtIdServico.setFocusable(false);

        jLabel2.setText("Data e hora");

        jtDatahora.setEditable(false);
        jtDatahora.setFocusable(false);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Paciente");

        jtPaciente.setEditable(false);
        jtPaciente.setText("jTextField2");
        jtPaciente.setFocusable(false);
        jtPaciente.setOpaque(false);

        javax.swing.GroupLayout panelServicoLayout = new javax.swing.GroupLayout(panelServico);
        panelServico.setLayout(panelServicoLayout);
        panelServicoLayout.setHorizontalGroup(
            panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelServicoLayout.createSequentialGroup()
                        .addComponent(jtIdServico, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtDatahora, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtPaciente))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        panelServicoLayout.setVerticalGroup(
            panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelServicoLayout.createSequentialGroup()
                        .addGroup(panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtIdServico))
                        .addGap(2, 2, 2))
                    .addGroup(panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtDatahora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Item"));

        jLabel3.setText("Tipo do serviço");

        jcTipoServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Quantidade");

        jtQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout panelItemLayout = new javax.swing.GroupLayout(panelItem);
        panelItem.setLayout(panelItemLayout);
        panelItemLayout.setHorizontalGroup(
            panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jcTipoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelItemLayout.setVerticalGroup(
            panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcTipoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jadsongonzaga/organize/view/icones/ic_add_box_black_18dp_1x.png"))); // NOI18N
        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jadsongonzaga/organize/view/icones/ic_add_to_photos_black_18dp_1x.png"))); // NOI18N
        jButton2.setText("Adicionar e continuar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        salvar(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        salvar(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicoItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicoItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicoItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicoItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServicoItemView dialog = new ServicoItemView(new javax.swing.JFrame(), true, new Servico());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jcTipoServico;
    private javax.swing.JTextField jtDatahora;
    private javax.swing.JTextField jtIdServico;
    private javax.swing.JTextField jtPaciente;
    private javax.swing.JFormattedTextField jtQuantidade;
    private javax.swing.JPanel panelItem;
    private javax.swing.JPanel panelServico;
    // End of variables declaration//GEN-END:variables

    
    private boolean novo = true;
    private final Servico servico;
    ServicoItemController controller = new ServicoItemController();
    
    private void iniciar() {

        modoInicial();
        carregarComboTipoServico();
        setServico(servico);
        
    }
    
     
    private void modoInicial() {
        UtilsView.limpaComponentes(panelItem);
        jcTipoServico.grabFocus();
        UtilsView.habilitaComponentes(panelItem, true);
        UtilsView.habilitaComponentes(panelServico, false);
        novo = true;
    }
    
    private void modoEditar() {
        jcTipoServico.setEnabled(false);
        jtQuantidade.setEnabled(true);
        jtQuantidade.grabFocus();
        novo = false;
    }
    
    private ServicoItem getServicoItem(){
        ServicoItem sevrItem = new ServicoItem();
        
        sevrItem.setServico(servico);
        sevrItem.setQuantidade(Utils.paraBigDecimal(jtQuantidade.getText()));
        sevrItem.setTipoServico((TipoServico) jcTipoServico.getSelectedItem());
        
        return sevrItem;
    }
    
    private void setServicoItem(ServicoItem servItem){
        
        jtQuantidade.setText(Utils.paraString(servItem.getQuantidade()));
        jcTipoServico.setSelectedItem(servItem.getTipoServico());

    }
    
    private void setServico(Servico serv){
        
        jtDatahora.setText(serv.getDataHoraCriacao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")));
        jtPaciente.setText(serv.getPaciente().toString());
        jtIdServico.setText(String.valueOf(serv.getId()));

    }

    private void carregarComboTipoServico(){
        TipoServicoController tipoCrt = new TipoServicoController();
        jcTipoServico.setModel(tipoCrt.obterModelCombo());
    }
    
    private void salvar(boolean add){
        
        List<ComponenteInfo> componentes = new LinkedList<>();
        componentes.add(new ComponenteInfo(jcTipoServico, "Tipo do Servico"));
        componentes.add(new ComponenteInfo(jtQuantidade, "Quantidade"));
        if(UtilsView.validaCamposObrigatorios(componentes)){
            ServicoItem servicoItem = getServicoItem();
            
            controller.salvar(servicoItem, novo);
            
            
            if(add){
                modoInicial();
            }else{
                UtilsView.habilitaComponentes(panelItem, false);
            }
        }
        
    }
    


}
