
package jadsongonzaga.organize.view;

import jadsongonzaga.organize.controller.ClinicaController;
import jadsongonzaga.organize.controller.TipoCancerController;
import jadsongonzaga.organize.controller.TratamentoController;
import jadsongonzaga.organize.controller.Utils;
import jadsongonzaga.organize.model.Clinica;
import jadsongonzaga.organize.model.Paciente;
import jadsongonzaga.organize.model.TipoCancer;
import jadsongonzaga.organize.model.Tratamento;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author jadson
 */
public class TratamentoView extends javax.swing.JDialog {

    /**
     * Creates new form AcompanhanteView
     * @param parent
     * @param modal
     * @param paciente
     */
    public TratamentoView(java.awt.Frame parent, boolean modal, Paciente paciente) {
        super(parent, modal);
        this.paciente = paciente;
        acao();
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraTarefa = new jadsongonzaga.organize.view.PanelBarraTarefa(eventos);
        panelTratamento = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jdDataDiagnostico = new com.toedter.calendar.JDateChooser();
        jchQuimioterapio = new javax.swing.JCheckBox();
        jchRadioterapio = new javax.swing.JCheckBox();
        jcTipoCancer = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcClinica = new javax.swing.JComboBox<>();
        jbAdicionarTIpoCancer = new javax.swing.JButton();
        jdAdicionarClinica = new javax.swing.JButton();
        jtbFinalizar = new javax.swing.JToggleButton();
        panelFinalizarTratamenteo = new javax.swing.JPanel();
        jdDataFinalizacao = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jcTipoFinalizacao = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tratamento");

        panelTratamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tratamento"));
        panelTratamento.setPreferredSize(new java.awt.Dimension(706, 226));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Identificador");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Data do diagnóstico");

        jtId.setEditable(false);
        jtId.setText("jTextField1");

        jchQuimioterapio.setText("Quimioterapia");
        jchQuimioterapio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jchRadioterapio.setText("Radioterapia");
        jchRadioterapio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jcTipoCancer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tipo do câncer");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Clínica");

        jcClinica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbAdicionarTIpoCancer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jadsongonzaga/organize/view/icones/ic_add_black_18dp_1x.png"))); // NOI18N
        jbAdicionarTIpoCancer.setToolTipText("Adicionar um tipo de câncer");
        jbAdicionarTIpoCancer.setPreferredSize(new java.awt.Dimension(27, 27));
        jbAdicionarTIpoCancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarTIpoCancerActionPerformed(evt);
            }
        });

        jdAdicionarClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jadsongonzaga/organize/view/icones/ic_add_black_18dp_1x.png"))); // NOI18N
        jdAdicionarClinica.setToolTipText("Adicionar uma clínica");
        jdAdicionarClinica.setPreferredSize(new java.awt.Dimension(27, 27));
        jdAdicionarClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdAdicionarClinicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTratamentoLayout = new javax.swing.GroupLayout(panelTratamento);
        panelTratamento.setLayout(panelTratamentoLayout);
        panelTratamentoLayout.setHorizontalGroup(
            panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTratamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTratamentoLayout.createSequentialGroup()
                        .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdDataDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTratamentoLayout.createSequentialGroup()
                                .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jcClinica, 0, 344, Short.MAX_VALUE)
                                    .addComponent(jcTipoCancer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbAdicionarTIpoCancer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdAdicionarClinica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelTratamentoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jchQuimioterapio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(jchRadioterapio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTratamentoLayout.setVerticalGroup(
            panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTratamentoLayout.createSequentialGroup()
                .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdAdicionarClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTratamentoLayout.createSequentialGroup()
                        .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdDataDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcTipoCancer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbAdicionarTIpoCancer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTratamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchQuimioterapio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchRadioterapio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtbFinalizar.setText("Finalizar Tratamento");
        jtbFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbFinalizarActionPerformed(evt);
            }
        });

        panelFinalizarTratamenteo.setBorder(javax.swing.BorderFactory.createTitledBorder("Finalizar tratamento"));

        jdDataFinalizacao.setToolTipText("Data de finzalização do tratamento");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Data de finalização");

        jcTipoFinalizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tipo de finalização");

        javax.swing.GroupLayout panelFinalizarTratamenteoLayout = new javax.swing.GroupLayout(panelFinalizarTratamenteo);
        panelFinalizarTratamenteo.setLayout(panelFinalizarTratamenteoLayout);
        panelFinalizarTratamenteoLayout.setHorizontalGroup(
            panelFinalizarTratamenteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalizarTratamenteoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinalizarTratamenteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(panelFinalizarTratamenteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdDataFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcTipoFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(283, 283, 283))
        );
        panelFinalizarTratamenteoLayout.setVerticalGroup(
            panelFinalizarTratamenteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalizarTratamenteoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinalizarTratamenteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdDataFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFinalizarTratamenteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcTipoFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(panelTratamento, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbFinalizar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panelFinalizarTratamenteo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBarraTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jtbFinalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFinalizarTratamenteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtbFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbFinalizarActionPerformed

        if(jtbFinalizar.isSelected()){
            this.setSize(new Dimension(755, 430));
        }else{
            this.setSize(new Dimension(755, 290));
        }
        
    }//GEN-LAST:event_jtbFinalizarActionPerformed

    private void jbAdicionarTIpoCancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarTIpoCancerActionPerformed

        
        addTipoCancer();
        
    }//GEN-LAST:event_jbAdicionarTIpoCancerActionPerformed

    private void jdAdicionarClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdAdicionarClinicaActionPerformed

        addClinica();
        
    }//GEN-LAST:event_jdAdicionarClinicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TratamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TratamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TratamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TratamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TratamentoView dialog = new TratamentoView(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbAdicionarTIpoCancer;
    private javax.swing.JComboBox<String> jcClinica;
    private javax.swing.JComboBox<String> jcTipoCancer;
    private javax.swing.JComboBox<String> jcTipoFinalizacao;
    private javax.swing.JCheckBox jchQuimioterapio;
    private javax.swing.JCheckBox jchRadioterapio;
    private javax.swing.JButton jdAdicionarClinica;
    private com.toedter.calendar.JDateChooser jdDataDiagnostico;
    private com.toedter.calendar.JDateChooser jdDataFinalizacao;
    private javax.swing.JTextField jtId;
    private javax.swing.JToggleButton jtbFinalizar;
    private jadsongonzaga.organize.view.PanelBarraTarefa panelBarraTarefa;
    private javax.swing.JPanel panelFinalizarTratamenteo;
    private javax.swing.JPanel panelTratamento;
    // End of variables declaration//GEN-END:variables

    
    TratamentoController controller = new TratamentoController();
    Tratamento tratamento;
    private boolean novo = true;
    Paciente paciente;
    EventosBarraTarefar eventos;

    private void iniciar() {

        modoInicial();
        carregarClinica();
        carregarTipoCancer();
        carregarTipoFinalizacao();
        this.setSize(new Dimension(755, 290));
        panelBarraTarefa.getJbPesquisar().setVisible(false);
        panelBarraTarefa.getJbNovo().setVisible(false);
        panelBarraTarefa.getJbExcluir().setVisible(false);
        
        if(paciente == null || paciente.getTratamento() == null){
            eventos.novo();
            panelBarraTarefa.habilitaEdicao();
        }else{
            tratamento = paciente.getTratamento();
            setTratamento(tratamento);
            panelBarraTarefa.modoBuscar();
        }

    }

    private Tratamento getTratamento() {
        Tratamento trat = new Tratamento();
        if(!jtId.getText().isEmpty())
            trat.setId(Integer.parseInt(jtId.getText()));
        trat.setDataDiagnostico(Utils.paraLocalDate(jdDataDiagnostico.getDate()));
        trat.setClinica((Clinica) jcClinica.getSelectedItem());
        trat.setTipoCancer((TipoCancer) jcTipoCancer.getSelectedItem());
        trat.setTipoFim((Tratamento.TipoFim) jcTipoFinalizacao.getSelectedItem());
        trat.setDataFimTratamento(Utils.paraLocalDate(jdDataFinalizacao.getDate()));
        trat.setRadioterapio(jchRadioterapio.isSelected());
        trat.setQuimioterapio(jchQuimioterapio.isSelected());
        trat.setPaciente(paciente);
        
        return trat;
    }
    
    private void setTratamento(Tratamento trat) {
  
        jtId.setText(String.valueOf(trat.getId()));
        jdDataDiagnostico.setDate(java.sql.Date.valueOf(trat.getDataDiagnostico()));
        jcClinica.setSelectedItem(trat.getClinica());
        jcTipoCancer.setSelectedItem(trat.getTipoCancer());
        jcTipoFinalizacao.setSelectedItem(trat.getTipoFim());
        jchQuimioterapio.setSelected(trat.isQuimioterapio());
        jchRadioterapio.setSelected(trat.isRadioterapio());
        if(trat.getDataFimTratamento() != null)
            jdDataFinalizacao.setDate(java.sql.Date.valueOf(trat.getDataFimTratamento()));
    }
    
    private void carregarDados(int id){
        tratamento = controller.obter(id);
        setTratamento(tratamento);
        
    }

    private void evtNovo() {
        UtilsView.limpaComponentes(panelTratamento);
        UtilsView.limpaComponentes(panelFinalizarTratamenteo);
    
        UtilsView.habilitaComponentes(panelTratamento, true);
        UtilsView.habilitaComponentes(panelFinalizarTratamenteo, true);
        jdDataDiagnostico.grabFocus();
       
    }
    
    private void modoInicial() {
        UtilsView.limpaComponentes(panelTratamento);
        UtilsView.limpaComponentes(panelFinalizarTratamenteo);
        jdDataDiagnostico.grabFocus();
        UtilsView.habilitaComponentes(panelTratamento, false);
        UtilsView.habilitaComponentes(panelFinalizarTratamenteo, false);
        novo = true;
    }
    
    private void modoEditar() {
        
        UtilsView.habilitaComponentes(panelTratamento, true);
        UtilsView.habilitaComponentes(panelFinalizarTratamenteo, true);
        jdDataDiagnostico.grabFocus();
    }
    
    private void carregarClinica() {
        jcClinica.setModel(new ClinicaController().obterModelCombo());
    }
    
    private void carregarTipoFinalizacao() {
        jcTipoFinalizacao.setModel(new TratamentoController().obterModelComboTipoFim());
    }

    private void carregarTipoCancer() {
        jcTipoCancer.setModel(new TipoCancerController().obterModelCombo());
    }
    
    private void addTipoCancer(){
        TipoCancerView tcv = new TipoCancerView(null, true);
        tcv.setVisible(true);
        carregarTipoCancer();
    }
    
    private void addClinica(){
        ClinicaView cv = new ClinicaView(null, true);
        cv.setVisible(true);
        carregarClinica();
    }
    
    public Tratamento getTratamentoSelecionado(){
        this.setVisible(true);
        return tratamento;
    }
    
     

    private void acao() {
        eventos = new EventosBarraTarefar() {
            @Override
            public boolean salvar() {

                tratamento = getTratamento();
          
                panelBarraTarefa.modoBuscaSalvar(true);
                controller.salvar(tratamento, novo);
                setTratamento(tratamento);
                UtilsView.habilitaComponentes(panelTratamento, false);
                return true;
            }

            @Override
            public void novo() {
                evtNovo();
            }

            @Override
            public void cancelar() {
                modoInicial();
            }

            @Override
            public void editar() {
                modoEditar();
                novo = false;
            }

            @Override
            public boolean excluir() {
                int op = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse registro?");
                if(op == 0){
                    controller.excluir(tratamento);
                    modoInicial();
                }
                return op == 0;
            }

            @Override
            public void pesquisar() {
                
            }

            @Override
            public void confirmar() {
                dispose();
            }
        };
    }
    
    
    
    
}
