INSERT INTO estado (id, nome) VALUES (11, 'Rondônia');
INSERT INTO estado (id, nome) VALUES (12, 'Acre');
INSERT INTO estado (id, nome) VALUES (13, 'Amazonas');
INSERT INTO estado (id, nome) VALUES (14, 'Roraima');
INSERT INTO estado (id, nome) VALUES (15, 'Pará');
INSERT INTO estado (id, nome) VALUES (16, 'Amapá');
INSERT INTO estado (id, nome) VALUES (17, 'Tocantins');
INSERT INTO estado (id, nome) VALUES (21, 'Maranhão');
INSERT INTO estado (id, nome) VALUES (22, 'Piauí');
INSERT INTO estado (id, nome) VALUES (23, 'Ceará');
INSERT INTO estado (id, nome) VALUES (24, 'Rio Grande do Norte');
INSERT INTO estado (id, nome) VALUES (25, 'Paraíba');
INSERT INTO estado (id, nome) VALUES (26, 'Pernambuco');
INSERT INTO estado (id, nome) VALUES (27, 'Alagoas');
INSERT INTO estado (id, nome) VALUES (28, 'Sergipe');
INSERT INTO estado (id, nome) VALUES (29, 'Bahia');
INSERT INTO estado (id, nome) VALUES (31, 'Minas Gerais');
INSERT INTO estado (id, nome) VALUES (32, 'Espírito Santo');
INSERT INTO estado (id, nome) VALUES (33, 'Rio de Janeiro');
INSERT INTO estado (id, nome) VALUES (35, 'São Paulo');
INSERT INTO estado (id, nome) VALUES (41, 'Paraná');
INSERT INTO estado (id, nome) VALUES (42, 'Santa Catarina');
INSERT INTO estado (id, nome) VALUES (43, 'Rio Grande do Sul');
INSERT INTO estado (id, nome) VALUES (50, 'Mato Grosso do Sul');
INSERT INTO estado (id, nome) VALUES (51, 'Mato Grosso');
INSERT INTO estado (id, nome) VALUES (52, 'Goiás');
INSERT INTO estado (id, nome) VALUES (53, 'Distrito Federal');
